# Generated by Django 4.0.1 on 2024-05-05 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_step_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 5, 20, 19, 11, 327224, tzinfo=utc), verbose_name='Recipe Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Recipe modified'),
        ),
    ]
