# Generated by Django 5.2.7 on 2025-11-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_recipes.recipeingredient')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_recipes.step')),
            ],
        ),
    ]
