# Generated by Django 6.0 on 2026-07-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_recipes', '0002_stepingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='component',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
